[versions]

#sdk
targetSdk = "30"
compileSdk = "30"
minSdk = "21"

gradle = "7.0.4"
kotlin = "1.5.31"
googleServices = "4.3.3"
firebaseCrashlyticsGradle = "2.5.2"
gradleVersionsPlugin = "0.39.0"

# AndroidX
appcompat = "1.3.1"
cardView = "1.0.0"
recyclerView = "1.1.0"
constraintLayout = "1.1.3"
room = "2.3.0"
androidXAnnotations = "1.0.1"
fragment-ktx = "1.3.6"
navigation = "2.3.5"
lifecycle = "2.3.1"
swiperefreshlayout = "1.0.0"
core-ktx = "1.5.0"
activity-ktx = "1.3.1"
browser = "1.2.0"
compose = "1.0.5"
flexbox = "2.0.1"
koin = "2.0.1"
coroutines = "1.5.2"
retrofit = "2.6.0"
converter-gson = "2.3.0"
logging-interceptor = "3.12.1"
glide = "4.12.0"
landscapist-glide = "1.4.0"
firebase-analytics = "17.4.2"
firebase-messaging = "20.2.0"
firebase-crashlytics = "17.0.0"
kotpref = "2.13.2"
photoView = "2.3.0"
indefinitePagerIndicator = "1.0.10"
timeago = "4.0.3"
swipeDecorator = "1.2.2"
persianDate = "0.8"
chucker = "3.2.0"
timber = "5.0.1"

[plugins]
androidapplication = { id = "com.android.application", version.ref = "gradleVersionsPlugin" }
androidlibrary = { id = "com.android.library", version.ref = "gradleVersionsPlugin" }
kotlinandroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinkapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
navigationsafeargs = { id = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation" }

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
cardView = { module = "androidx.cardview:cardview", version.ref = "cardView" }
recyclerView = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerView" }
constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
roomRuntime = { module = "androidx.room:room-runtime", version.ref = "room" }
roomKtx = { module = "androidx.room:room-ktx", version.ref = "room" }
roomCompiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidXAnnotations = { module = "androidx.annotation:annotation", version.ref = "androidXAnnotations" }
fragmentKtx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment-ktx" }
navigationFragmentKtx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigationUiKtx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
navitationRuntimeKtx = { module = "androidx.navigation:navigation-runtime-ktx", version.ref = "navigation" }
lifecycleProcess = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
lifecycleLivedataKtx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycleViewmodelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycleCompiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "lifecycle" }
swipeRefreshLayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
coreKtx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
activityKtx = { module = "androidx.core:core-ktx", version.ref = "activity-ktx" }
browser = { module = "androidx.browser:browser", version.ref = "browser" }
composeUi = { module = "androidx.compose.ui:ui", version.ref = "compose" }
composeUiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
composeFoundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
composeRuntimeLivedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
composeMaterial = { module = "androidx.compose.material:material", version.ref = "compose" }
composeThemeAdapter = { module = "com.google.android.material:compose-theme-adapter", version.ref = "compose" }
flexbox = { module = "com.google.android:flexbox", version.ref = "flexbox" }
koin = { module = "org.koin:koin-android-viewmodel", version.ref = "koin" }
coroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converterGson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converter-gson" }
loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "logging-interceptor" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glideCompiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
landscapistGlide = { module = "com.github.skydoves:landscapist-glide", version.ref = "landscapist-glide" }
firebaseAnalytics = { module = "com.google.firebase:firebase-analytics", version.ref = "firebase-analytics" }
firebaseMessaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebase-messaging" }
firebaseCrashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebase-crashlytics" }
kotpref = { module = "com.chibatching.kotpref:kotpref", version.ref = "kotpref" }
kotprefGsonSupport = { module = "com.chibatching.kotpref:gson-support", version.ref = "kotpref" }
kotprefInitializer = { module = "com.chibatching.kotpref:initializer", version.ref = "kotpref" }
kotprefLivedataSupport = { module = "com.chibatching.kotpref:livedata-support", version.ref = "kotpref" }
photoView = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoView" }
indefinitePagerIndicator = { module = "com.ryanjeffreybrooks:indefinitepagerindicator", version.ref = "indefinitePagerIndicator" }
timeago = { module = "com.github.marlonlom:timeago", version.ref = "timeago" }
swipeDecorator = { module = "it.xabaras.android:recyclerview-swipedecorator", version.ref = "swipeDecorator" }
persianDate = { module = "com.github.samanzamani.persiandate:PersianDate", version.ref = "persianDate" }
chuckerLibrary = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
chuckerLibraryNoOp = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chucker" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[bundles]
room = ["roomRuntime", "roomKtx", "roomCompiler"]
navigation = ["navigationFragmentKtx", "navigationUiKtx", "navitationRuntimeKtx"]
lifecycle = ["lifecycleProcess", "lifecycleLivedataKtx", "lifecycleViewmodelKtx", "lifecycleCompiler"]
compose = ["composeUi", "composeUiTooling", "composeFoundation", "composeRuntimeLivedata", "composeMaterial"]
coroutines = ["coroutinesAndroid", "coroutinesCore"]
retrofit = ["retrofit", "converterGson"]
glide = ["glide", "glideCompiler"]
firebase = ["firebaseAnalytics", "firebaseMessaging", "firebaseCrashlytics"]
kotpref = ["kotpref", "kotprefGsonSupport", "kotprefInitializer", "kotprefLivedataSupport"]
