name: Telegram Notifier

on:
  push:
    branches:
      - master

jobs:
  notify:
    name: Notify via Telegram
    runs-on: ubuntu-latest
    steps:
      - name: Building message
        id: building_message
        run: |
          jsonGithub='${{toJson(github.event)}}'
          commits=$(echo $jsonGithub | jq '.commits')
          length=$(echo $commits | jq 'length')
          
          outMessage=""
          for (( i = 0; i < length; i++ )); do
            commit=$(echo $commits | jq '.['$i']')
            url=$(echo $commit | jq -r '.url')
            sha=$(echo $commit | jq -r '.id')
            sha=${sha:0:8}
            message=$(echo $commit | jq -r '.message')
            actor=$(echo $commit | jq -r '.author.username')
          
            outMessage+="<a href="\"$url\"">$sha</a> • <a href="\"https://github.com/$actor\"">$actor</a>"
            outMessage+="%0A"
            outMessage+=$message
            outMessage+="%0A%0A"
          done

          echo $outMessage
          echo "::set-output name=message::$outMessage"

      - name: Send message to Telegram
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: html
          message: |
            ${{steps.building_message.outputs.message}}
            @Kindnesswall_Android_App
